import { Subject } from 'rxjs';
import { Scene } from '@khanonjs/engine';
import { AppSceneProperties } from '../app-scene-properties';
import { SceneIntroActionGravity } from './actions/action-gravity';
import { EarthActor } from './actors/earth/earth-actor';
import { LogoActor } from './actors/logo/logo-actor';
import { RobocilloActor } from './actors/robocillo/robocillo-actor';
import { SunActor } from './actors/sun/sun-actor';
import { SceneIntroGlobals } from './scene-intro-globals';
export declare class SceneIntro extends Scene {
    protected readonly properties: AppSceneProperties;
    static id: string;
    id: string;
    private readonly START_RATIO_CANVAS;
    private readonly MIDDLE_RATIO_CANVAS;
    private readonly END_RATIO_CANVAS;
    private readonly VERTICAL_RATIO_CANVAS;
    private readonly paramsRatio0CameraPos;
    private readonly paramsRatio1CameraPos;
    canvasRatio: number;
    private camera;
    private light;
    sceneIntroShared: SceneIntroGlobals;
    earth: EarthActor;
    logo: LogoActor;
    sun: SunActor;
    robocillo: RobocilloActor;
    gravity: SceneIntroActionGravity;
    worldLoaded: boolean;
    onWorldLoaded$: Subject<void>;
    private loadingEndTx;
    private readonly loadingEndTexts;
    private goWorldHandler;
    constructor(properties: AppSceneProperties);
    onLoad(): void;
    onPlay(): void;
    onStop(): void;
    onRelease(): void;
    onError(errorMsg: string): void;
    onGoWorld(): void;
    subscribeCanvasResize(): void;
    applyCanvasRatio(initialize: boolean): void;
    onWorldLoaded(): void;
}
